### ISSUE TITLE
DMABUF_IMPORT not working with tiovx plugins

### ISSUE THREAD

**Issue by p-mantena** [TexasInstruments/edgeai-gst-plugins#214]
Hi,

We have  dma buffer import mode in the v4l2 decoder. With tiovx plugins, we are facing issue. There are no suspectable debugs coming out from the GST_DEBUG even. The pipeline hangs and becomes redundant without starting anything.

_Working Pipelines_

gst-launch-1.0 filesrc location=/opt/edge_ai_apps/data/videos/video_0000_h264.mp4 ! qtdemux ! h264parse ! v4l2h264dec capture-io-mode=5 ! video/x-raw, format=NV12 ! kmssink sync=false

gst-launch-1.0 filesrc location=/opt/edge_ai_apps/data/videos/video_0000_h264.mp4 ! qtdemux ! h264parse ! v4l2h264dec capture-io-mode=5 ! video/x-raw, format=NV12 ! **videoscale** ! video/x-raw, format=NV12 ! kmssink sync=false

_Non Working Pipeline_  - The video stream doesn’t even start.

gst-launch-1.0 filesrc location=/opt/edge_ai_apps/data/videos/video_0000_h264.mp4 ! qtdemux ! h264parse ! v4l2h264dec capture-io-mode=5 ! video/x-raw, format=NV12 ! **tiovxmultiscaler** ! video/x-raw, format=NV12 ! kmssink sync=false

Regards,
Prasanth

**Comment by m-herrera** [comment]
Hi @p-mantena, @ravi-rahul, this issue is related to the pool size being used; by default all tiovx elements have a pool size of 2 and the decoder seems to hold more buffers than that so the pipeline hangs, this can be fixed by increasing the size of the tiovxmultiscaler sink pool to 8.

```
gst-launch-1.0 filesrc location=/opt/edge_ai_apps/data/videos/video_0000_h264.mp4 !  \
qtdemux ! h264parse ! v4l2h264dec capture-io-mode=5 ! video/x-raw, format=NV12 !     \
tiovxmultiscaler sink::pool-size=8 ! video/x-raw, format=NV12 ! kmssink sync=false
```

Please give this a try and let us know if the issue persists, otherwise feel free to close it.
